# Generated by Django 6.0.6 on 2026-06-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Stable identifier for lookups, unaffected by renaming 'name'",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Code",
            ),
        ),
    ]
