# Generated by Django 6.0.6 on 2026-06-21 13:10

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_role_code"),
        ("base", "0003_remove_state_state_alter_country_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="state",
            field=models.ForeignKey(
                blank=True,
                default=base.models.get_default_state,
                help_text="The current state of this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="base.state",
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Stable identifier for lookups, unaffected by renaming 'name'",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="state",
            field=models.ForeignKey(
                blank=True,
                default=base.models.get_default_state,
                help_text="The current state of this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="base.state",
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="state",
            field=models.ForeignKey(
                blank=True,
                default=base.models.get_default_state,
                help_text="The current state of this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="base.state",
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.ForeignKey(
                blank=True,
                default=base.models.get_default_state,
                help_text="The current state of this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="base.state",
                verbose_name="State",
            ),
        ),
    ]
