# Generated by Django 6.0.6 on 2026-06-20 21:12

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_country_code_state_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="state",
            name="state",
        ),
        migrations.AlterField(
            model_name="country",
            name="state",
            field=models.ForeignKey(
                blank=True,
                default=base.models.get_default_state,
                help_text="The current state of this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="base.state",
                verbose_name="State",
            ),
        ),
    ]
