# Generated by Django 6.0.6 on 2026-06-18 19:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="patients/avatars/",
                        verbose_name="Profile Photo",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Biography"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Include country code e.g. +254712345678",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must include country code e.g. '+254712345678', '+12125552368', '+441234567890'. Between 7 and 15 digits after '+'.",
                                regex="^\\+[1-9]\\d{6,14}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Emergency Contact Name",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must include country code e.g. '+254712345678', '+12125552368', '+441234567890'. Between 7 and 15 digits after '+'.",
                                regex="^\\+[1-9]\\d{6,14}$",
                            )
                        ],
                        verbose_name="Emergency Contact Phone",
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Emergency Contact Relationship",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A Positive"),
                            ("A-", "A Negative"),
                            ("B+", "B Positive"),
                            ("B-", "B Negative"),
                            ("AB+", "AB Positive"),
                            ("AB-", "AB Negative"),
                            ("O+", "O Positive"),
                            ("O-", "O Negative"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Blood Type",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allergies",
                        null=True,
                        verbose_name="Allergies",
                    ),
                ),
                (
                    "chronic_conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of chronic conditions",
                        null=True,
                        verbose_name="Chronic Conditions",
                    ),
                ),
                (
                    "current_medications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of current medications",
                        null=True,
                        verbose_name="Current Medications",
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional medical information",
                        null=True,
                        verbose_name="Medical Notes",
                    ),
                ),
                (
                    "share_medical_history",
                    models.BooleanField(
                        default=True,
                        help_text="Allow consultants to view medical history",
                        verbose_name="Share Medical History",
                    ),
                ),
                (
                    "allow_emergency_access",
                    models.BooleanField(
                        default=True,
                        help_text="Allow emergency personnel to access medical information",
                        verbose_name="Allow Emergency Access",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="Preferred Language"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="The current state of this record",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="base.state",
                        verbose_name="State",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role__name": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
                "db_table": "patient_profiles",
            },
        ),
        migrations.CreateModel(
            name="PatientMedicalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("diagnosis", "Diagnosis"),
                            ("procedure", "Medical Procedure"),
                            ("surgery", "Surgery"),
                            ("hospitalization", "Hospitalization"),
                            ("vaccination", "Vaccination"),
                            ("test_result", "Test Result"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Record Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "date_occurred",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Occurred"
                    ),
                ),
                (
                    "healthcare_provider",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Healthcare Provider",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of attached file URLs or references",
                        null=True,
                        verbose_name="Attachments",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="The current state of this record",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="base.state",
                        verbose_name="State",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history",
                        to="patients.patientprofile",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_medical_history",
                "ordering": ["-date_occurred", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="patientprofile",
            index=models.Index(fields=["user"], name="patient_pro_user_id_27548b_idx"),
        ),
        migrations.AddIndex(
            model_name="patientprofile",
            index=models.Index(
                fields=["created_at"], name="patient_pro_created_2ba952_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientprofile",
            index=models.Index(
                fields=["blood_type"], name="patient_pro_blood_t_c3c270_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientprofile",
            index=models.Index(fields=["gender"], name="patient_pro_gender_81fe78_idx"),
        ),
        migrations.AddIndex(
            model_name="patientprofile",
            index=models.Index(
                fields=["country"], name="patient_pro_country_04b31d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientmedicalhistory",
            index=models.Index(
                fields=["patient"], name="patient_med_patient_c5f002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientmedicalhistory",
            index=models.Index(
                fields=["record_type"], name="patient_med_record__ee1f42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientmedicalhistory",
            index=models.Index(
                fields=["date_occurred"], name="patient_med_date_oc_3252b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientmedicalhistory",
            index=models.Index(
                fields=["patient", "record_type"], name="patient_med_patient_284122_idx"
            ),
        ),
    ]
