# Generated by Django 6.0.6 on 2026-06-18 19:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="The current state of this record",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="base.state",
                        verbose_name="State",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Specialties",
                "db_table": "specialities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="consultants/avatars/"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Biography"
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="Years of Experience",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="License Number",
                    ),
                ),
                (
                    "medical_degree",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Medical Degree",
                    ),
                ),
                (
                    "board_certifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of board certifications",
                        verbose_name="Board Certifications",
                    ),
                ),
                (
                    "additional_qualifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of additional qualifications",
                        verbose_name="Additional Qualifications",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Include country code e.g. +254712345678",
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must include country code e.g. '+254712345678', '+12125552368', '+441234567890'. Between 7 and 15 digits after '+'.",
                                regex="^\\+[1-9]\\d{6,14}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Clinic Name",
                    ),
                ),
                (
                    "clinic_address",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Clinic Address",
                    ),
                ),
                (
                    "clinic_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Clinic City",
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Consultation Fee",
                    ),
                ),
                (
                    "consultation_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        default=30,
                        help_text="Default consultation duration in minutes",
                        null=True,
                        verbose_name="Consultation Duration",
                    ),
                ),
                (
                    "consultation_types",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("video", "Video Consultation"),
                            ("audio", "Audio Only"),
                            ("chat", "Text Chat"),
                            ("all", "All Types"),
                        ],
                        default="all",
                        max_length=10,
                        null=True,
                        verbose_name="Consultation Types",
                    ),
                ),
                (
                    "languages_spoken",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of languages the consultant speaks",
                        verbose_name="Languages Spoken",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "availability_schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Weekly schedule with time slots",
                        verbose_name="Availability Schedule",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "total_consultations",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Total Consultations",
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Total Reviews"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured consultants appear at the top of search results",
                        verbose_name="Featured",
                    ),
                ),
                (
                    "clinic_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.country",
                        verbose_name="Clinic Country",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="The current state of this record",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="base.state",
                        verbose_name="State",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role__name": "consultant"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultants",
                        to="consoltants.speciality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultant Profile",
                "verbose_name_plural": "Consultant Profiles",
                "db_table": "consultant_profiles",
            },
        ),
        migrations.CreateModel(
            name="ConsultantAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="The current state of this record",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="base.state",
                        verbose_name="State",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="consoltants.consultantprofile",
                        verbose_name="Consultant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultant Availability",
                "verbose_name_plural": "Consultant Availabilities",
                "db_table": "consultant_availability",
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["consultant", "day_of_week"],
                        name="consultant__consult_e47fb7_idx",
                    ),
                    models.Index(
                        fields=["day_of_week", "start_time"],
                        name="consultant__day_of__1ed5f0_idx",
                    ),
                ],
                "unique_together": {
                    ("consultant", "day_of_week", "start_time", "end_time")
                },
            },
        ),
        migrations.CreateModel(
            name="ConsultantReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "review_text",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Review"
                    ),
                ),
                (
                    "is_verified_consultation",
                    models.BooleanField(
                        default=False,
                        help_text="Review is from a confirmed consultation",
                        verbose_name="Verified Consultation",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Hide patient name from public view",
                        verbose_name="Anonymous",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="consoltants.consultantprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__name": "patient"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Patient",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="The current state of this record",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="base.state",
                        verbose_name="State",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultant Review",
                "verbose_name_plural": "Consultant Reviews",
                "db_table": "consultant_reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["consultant", "rating"],
                        name="consultant__consult_a003a4_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="consultant__created_22c96a_idx"
                    ),
                    models.Index(
                        fields=["is_verified_consultation"],
                        name="consultant__is_veri_cf3555_idx",
                    ),
                ],
                "unique_together": {("consultant", "patient")},
            },
        ),
        migrations.AddIndex(
            model_name="consultantprofile",
            index=models.Index(fields=["user"], name="consultant__user_id_9d3cb9_idx"),
        ),
        migrations.AddIndex(
            model_name="consultantprofile",
            index=models.Index(
                fields=["speciality"], name="consultant__special_e83615_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantprofile",
            index=models.Index(
                fields=["is_verified", "is_available"],
                name="consultant__is_veri_0e3438_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultantprofile",
            index=models.Index(
                fields=["created_at"], name="consultant__created_c174b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantprofile",
            index=models.Index(fields=["rating"], name="consultant__rating_8d9f6a_idx"),
        ),
    ]
