# Generated by Django 6.0.6 on 2026-06-21 13:10

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_state_state_alter_country_state"),
        ("consoltants", "0002_speciality_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultantavailability",
            name="state",
            field=models.ForeignKey(
                blank=True,
                default=base.models.get_default_state,
                help_text="The current state of this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="base.state",
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="consultantprofile",
            name="state",
            field=models.ForeignKey(
                blank=True,
                default=base.models.get_default_state,
                help_text="The current state of this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="base.state",
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="consultantreview",
            name="state",
            field=models.ForeignKey(
                blank=True,
                default=base.models.get_default_state,
                help_text="The current state of this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="base.state",
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="state",
            field=models.ForeignKey(
                blank=True,
                default=base.models.get_default_state,
                help_text="The current state of this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="base.state",
                verbose_name="State",
            ),
        ),
    ]
